### ISSUE TITLE
Rapport terminé.

### ISSUE THREAD

**Issue by dylan-marsangy** [PolytechLyon/isi3-tp-singleton-singleton_marsangy_rocchia#1]
Bonjour,

Nous avons conclu le rapport de ce TP Singleton. Nous attendons votre retour.

Merci d'avance.

Cordialement,
MARSANGY Dylan et ROCCHIA Alicia.

**Comment by Slashgear** [comment]
- A quoi sert le paramètre abstract
Je parle du mot clé dans la configuration des bean, votre réponse n'est donc pas correct.

- votre définition de l'autowiring n'est pas correcte.

**Comment by AliciaRocchia** [comment]
Bonjour,

Merci pour votre retour, nous avons rectifié nos réponses !

Cordialement

**Comment by dylan-marsangy** [comment]
Bonjour @Slashgear, nous vous relançons notre rapport de TP.

Cordialement.
